In [2]:
import pandas as pd

In [3]:
ds = pd.read_csv('ds_hati.csv')
ds

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [4]:
ds.describe()
pd.unique(ds['output'])

array([1, 0], dtype=int64)

In [5]:
ds['output'].value_counts()

output
1    165
0    138
Name: count, dtype: int64

In [6]:
ds.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
restecg       int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

In [7]:
x= ds.drop(columns='output', axis=1)
y= ds['output']
x

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  
0      0      1  
1      0      2  
2      0      2  
3      0      2  
4      0      2  
..   ...    ...  
298    0      3  
299    0      3  
300    2      3  
301    1      3  
302    1      2  

[303 rows x 13 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.2 , random_state=99)

In [9]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

model.fit(x_train,y_train)

GaussianNB()

In [10]:
y_prediksi = model.predict(x_test)
y_prediksi

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [11]:
import numpy as np
np.array(y_test)

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [12]:
from sklearn.metrics import accuracy_score
print("Nilai Akurasi", accuracy_score(y_test,y_prediksi))

Nilai Akurasi 0.9016393442622951


In [13]:
databaru = pd.read_excel('db_hati.xlsx')
newdata = databaru.iloc[:,:]


newprediksi = model.predict(newdata)
print("Hasil prediksi: \n")
for i, prediksi in enumerate(newprediksi,start=1):
    newdata_baris= newdata.iloc[i-1]
    print(f"Data uji ke- {i}: {newdata_baris.tolist()} = \"{prediksi}\"")


Hasil prediksi: 

Data uji ke- 1: [42.0, 1.0, 2.0, 145.0, 233.0, 1.0, 0.0, 168.0, 0.0, 1.6, 2.0, 0.0, 2.0] = "1"
Data uji ke- 2: [61.0, 1.0, 1.0, 130.0, 250.0, 0.0, 1.0, 169.0, 0.0, 6.2, 2.0, 4.0, 3.0] = "0"
Data uji ke- 3: [40.0, 0.0, 3.0, 130.0, 204.0, 0.0, 0.0, 159.0, 0.0, 0.0, 2.0, 1.0, 1.0] = "1"
Data uji ke- 4: [71.0, 0.0, 1.0, 105.0, 360.0, 0.0, 1.0, 138.0, 1.0, 1.2, 1.0, 0.0, 1.0] = "1"
Data uji ke- 5: [59.0, 0.0, 2.0, 120.0, 308.0, 0.0, 0.0, 111.0, 0.0, 2.6, 1.0, 0.0, 2.0] = "0"
Data uji ke- 6: [51.0, 1.0, 0.0, 130.0, 245.0, 0.0, 1.0, 157.0, 0.0, 2.0, 1.0, 0.0, 2.0] = "1"
Data uji ke- 7: [65.0, 1.0, 2.0, 125.0, 208.0, 1.0, 1.0, 147.0, 1.0, 0.0, 2.0, 3.0, 2.0] = "0"
Data uji ke- 8: [53.0, 0.0, 1.0, 125.0, 264.0, 0.0, 0.0, 162.0, 0.0, 0.4, 2.0, 1.0, 2.0] = "1"
Data uji ke- 9: [54.0, 1.0, 1.0, 142.0, 321.0, 0.0, 1.0, 173.0, 0.0, 3.6, 2.0, 3.0, 2.0] = "0"
Data uji ke- 10: [65.0, 1.0, 0.0, 135.0, 325.0, 0.0, 1.0, 178.0, 0.0, 1.2, 2.0, 2.0, 2.0] = "1"
Data uji ke- 11: [65.0, 1.0, 2.